### PR TITLE
Added style elements to category pages

### PR DESCRIPTION
**Pull request by jlora23**

### CODE REVIEW

**Comment by jlora23** [comment]
I only added the resizing style elements to the category pages (books, clothing, etc.).

**Comment by dcarpenter31** [comment]
What if we move this into a .css file? that way if we wanted to make a change it wouldn't need to be changed six times

**Comment by elenirotsides** [comment]
I'm in agreement with @carpenterd777

**Comment by jlora23** [comment]
I attempted to do use a css file (with the assistance of Eleni); however, we were unable to get it to work without it introducing much more work to be done. Essentially, the current method I am using to override the styling from the bootstrap is the easiest since doing it with css would force us to make many changes to each html file. At least for now I believe it is best to keep the solution as is, especially in preparation for the Wednesday due date.

**Comment by dcarpenter31** [comment]
ah I see. that's interesting, I guess we'll have to keep that in mind moving forward

**Review by dcarpenter31 — APPROVED** [review]

**Pull request merged**
