### PR TITLE
Continuous Integration

### PR DESCRIPTION
**Pull request by dcarpenter31**
This allows Github to automatically run a formatter and linter to see if our code adheres to some format and style that we can specify by changing the settings in `.pylintrc`. It encourages the use of a tool called `yapf` to encourage a consistent format. Finally, it will also run unit tests we create to test the functionality of types we have. 

- renamed types to e4s types
- added example test
- Add pylintrc
- Move tests into src dir
- Add yaml file for github CI

### CODE REVIEW

**Comment by dcarpenter31** [comment]
~~Do not merge this yet, there seems to be a problem~~

**Comment by elenirotsides** [comment]
@carpenterd777 How would you suggest this be tested? Should I even bother testing it? Let me know what you think!

**Comment by dcarpenter31** [comment]
Screenshot from 2021-03-22 20-32-04 <---- These are the CI checks! 

The `lint` check ensures that our code is formatted with `yapf` and obeys the styling guidelines suggested by `pylint`. We can change the styling guidelines by editing the `.pylintrc`.

The `test` check runs a trivial example unit test I wrote. Its in `src/tests/main.py`. As we add more tests, those will be run automatically without having to make any change to the `test` check.

If you want to see what file I added that makes Github run these checks (and exactly what commands those checks are) take a look at `.github/workflows/test.yml`. All of those commands are ones you can run in your terminal. That could be one way that you test that the CI is setup correctly or in a way palatable to our team. 

The main idea is that once this is set up, we can rely on it to tell us first if there any problems with our code before having a teammate review it.

**Comment by elenirotsides** [comment]
Oh I understand! This is really awesome, thanks for doing this! I have a follow up question: not sure if this is related, but does this override my `prettier` code formatter settings? I've had a problem in the past where I would save and push up my code, but it would reformat the whole file I touched, so it gave inaccurate 'lines changed' information to git as a result. We had to add a workspace prettier config file and that solved the problem, but is this an alternative way of doing it? @carpenterd777 (We obviously took the simplest approach bc we were strapped for time lol)

**Comment by dcarpenter31** [comment]
Does `prettier` edit python files automatically by default? `yapf` is basically `prettier` for Python

**Comment by elenirotsides** [comment]
Oh that's a good point hahaha it might not, I gotta check! I think I might have another formatter installed for python (probably installed it when vs code asked me if I wanted to install the recommended extensions for python 😂 ) Worst case scenario, I'll just disable my workspace settings!

**Comment by elenirotsides** [comment]
whoops.... I hit the wrong button....didn't mean to close the pr before 🤦🏻‍♀️

**Review by elenirotsides — APPROVED** [review]

**Pull request merged**
